### ISSUE TITLE
train with custom data

### ISSUE THREAD

**Issue by ggfresh** [SangbumChoi/MobileHumanPose#12]
hi, thanks for sharing the great job. If using custom data, what pre-process should I do? For example, normalizing the 3D coordinate data into [2000,2000,2000], normalizing the 2D data into [256, 256]?

**Comment by SangbumChoi** [comment]
@ggfresh well the data preparation should in MSCOCO format https://cocodataset.org/#format-data and also it depends on whether your dataset is formed as 2D or 3D
