### ISSUE TITLE
could you please share onnx model by google drive?

### ISSUE THREAD

**Issue by luohuan2uestc** [SangbumChoi/MobileHumanPose#13]
thanks.

**Comment by SangbumChoi** [comment]
I have shared few people via personal email but I will consider to open it in public. (Can't guarantee)

**Comment by luohuan2uestc** [comment]
> I have shared few people via personal email but I will consider to open it in public. (Can't guarantee)
I have wrote a request email to danielsejong55@gmail.com，
but no reply was received.
could you pls send  me onnx model to my email(luohuan1994@gmail.com).
Thanks a lot.

**Comment by SangbumChoi** [comment]
@luohuan2uestc Please consider to close this issue, since It solved :)

**Comment by PINTO0309** [comment]
@SangbumChoi Thank you for sharing your wonderful repository!

The tflite generated using **[onnx-tensorflow](https://github.com/onnx/tensorflow-onnx)** does not provide sufficient performance because it generates a lot of unnecessary **`Transpose`**. Therefore, I would like to contribute by further optimizing your model and tuning its performance using **[openvino2tensorflow](https://github.com/PINTO0309/openvino2tensorflow)**, an optimization tool I created myself. My tool is capable of converting a model in NCHW format to NHWC format completely.

If it's not too much trouble, could you please share ONNX with me? (rmsdh122@yahoo.co.jp)

I am going to provide you with a tflite that I have generated with maximum optimization. :smile:

**Comment by SangbumChoi** [comment]
> @SangbumChoi Thank you for sharing your wonderful repository!
> 
> The tflite generated using **[onnx-tensorflow](https://github.com/onnx/tensorflow-onnx)** does not provide sufficient performance because it generates a lot of unnecessary **`Transpose`**. Therefore, I would like to contribute by further optimizing your model and tuning its performance using **[openvino2tensorflow](https://github.com/PINTO0309/openvino2tensorflow)**, an optimization tool I created myself. My tool is capable of converting a model in NCHW format to NHWC format completely.
> 
> If it's not too much trouble, could you please share ONNX with me? ([s00856kh@gamil.com](mailto:s00856kh@gamil.com))
> 
> I am going to provide you with a tflite that I have generated with maximum optimization. 😄
> 
> * NCHW (ONNX) to NHWC (tflite), Maximum optimization sample
>   https://github.com/PINTO0309/openvino2tensorflow#8-model-structure

Yeah I am aware with the problem of transpose problem. But I think I have also send you ONNX file didn't I?

**Comment by PINTO0309** [comment]
@SangbumChoi I first discovered the existence of your repository 25 minutes ago. This is the first time I'm contacting you.

**Comment by SangbumChoi** [comment]
> @SangbumChoi I first discovered the existence of your repository 25 minutes ago. This is the first time I'm contacting you.

Oh, there are two another people requesting onnx model so i'm confused sorry. I will send you immediately

**Comment by PINTO0309** [comment]
Thank you! :smile_cat:

**Comment by SangbumChoi** [comment]
> Thank you! 😸

I have sent you email but it says (s00856kh@gamil.com) this e-mail won't work. Can you verify it again?

**Comment by PINTO0309** [comment]
Sorry... s00856kh@gmail.com

**Comment by SangbumChoi** [comment]
@PINTO0309 Please check again :)

**Comment by PINTO0309** [comment]
I got it! Thank you! I will optimize it as soon as I eat dinner and email the results to you. By the way, I would like to present this wonderful model converted to tflite in my repository, is there a problem?

- A repository that shares tuning results of trained models generated by TensorFlow / Keras. Post-training quantization (Weight Quantization, Integer Quantization, Full Integer Quantization, Float16 Quantization), Quantization-aware training. TensorFlow Lite. OpenVINO. CoreML. TensorFlow.js. TF-TRT. MediaPipe. ONNX.
https://github.com/PINTO0309/PINTO_model_zoo

**Comment by SangbumChoi** [comment]
Sounds great. No problem

Additionally, It would be wonderful if I get any chance to see some
progress during QAT or Dynamic and Static Quantization. (e.g. *code* or
evaluation score or inference speed difference) Because currently I am
learning those kind of techniques.

Thanks

**Comment by PINTO0309** [comment]
:+1: 

https://user-images.githubusercontent.com/33194443/134776082-dd1ab371-b78f-4d59-ad5b-5eec70caa432.mp4

![Screenshot 2021-09-25 23:28:50](https://user-images.githubusercontent.com/33194443/134776110-27b88c1b-9edd-458a-8bb5-1dcd681e4549.png)
