### ISSUE TITLE
PreTrained Model?

### ISSUE THREAD

**Issue by Momilijaz96** [SangbumChoi/MobileHumanPose#15]
Is there a pre-trained model available for the 3D pose extraction?

**Comment by SangbumChoi** [comment]
@Momilijaz96 I will release in public in soon, but if you want earlier then email me plz :)

**Comment by zuozhen** [comment]
> @Momilijaz96 I will release in public in soon, but if you want earlier then email me plz :)

Cool! 
Could I get a copy of the pre-trained pt model? I sent you email, please check :)

**Comment by zuozhen** [comment]
> 

Received from @SangbumChoi , thx.

**Comment by Patricia1019** [comment]
I want a pretrained model, too. Could you email me one? My email address is peiqiyu1019@gmail.com, thank you very much @SangbumChoi
