### ISSUE TITLE
why the output of the network is 64*64*(18*64)

### ISSUE THREAD

**Issue by SatMa34** [SangbumChoi/MobileHumanPose#18]
Thanks for your great work!
But i'm confused about the output of the network, your paper said the output is 64*64*1152 which means (output_res*output_res*(joint_num*64)), what dose this 64 mean? And what it stands for?

**Comment by SatMa34** [comment]
And what dose the depth_dim in cfg mean?

**Comment by tucan9389** [comment]
> And what dose the depth_dim in cfg mean?

As far as I know, for the z value, it was used. Bigger depth_dim, more precisely representable the z value.

**Comment by SatMa34** [comment]
> > And what dose the depth_dim in cfg mean?
> 
> As far as I know, for the z value, it was used. Bigger depth_dim, more precisely representable the z value.
Thanks for your reply, i know it is used in computing the z value, but how you get the z value by the heatmap, it doesn't seem to be stated in the paper

**Comment by SangbumChoi** [comment]
@SatMa34 
Voxel_dimension = 64
num_joint = 18
64*64*(18*64) is generated without softmax, after soft-maxing(?) each axis the output comes as 18*3

**Comment by tkddnjs98** [comment]
I found dimension of output (8, joints num, 3) after soft-maxing.

Input Image was(1, 3, 256, 256) --> batch size, channel, input_dim, input_dim
Is there any mistake I made?
