### ISSUE TITLE
Thank you for your excellent work. Can I get a pytorch pretrained weight file

### ISSUE THREAD

**Issue by liuguicen** [SangbumChoi/MobileHumanPose#19]
I need the smallest model. My email is 2583657917@qq.com , thank you again

**Comment by SangbumChoi** [comment]
@liuguicen still refactoring code for the best implementation and performance. Sorry for the late

**Comment by chandelarvind** [comment]
@SangbumChoi  I also need the pretrained weight file, mailed you regarding same. my email id is 
chandel.ash2004@gmail.com

**Comment by fanyhchn** [comment]
I need the model too, please , my email is fanyhchn@gmail.com
