### ISSUE TITLE
Pretrained model is not there yet?

### ISSUE THREAD

**Issue by AivisStud** [SangbumChoi/MobileHumanPose#21]
Dear SangbumChoi,

In repository it is said that there is pretrained model of your work. but I can not find it (I'm new to github community).
Could you please guide me in the right direction where to find it or if it is not there could you share it with me. I would like to test it out and see how it works.

I managed to find ONNX version of your work in:
https://github.com/PINTO0309/PINTO_model_zoo/blob/main/156_MobileHumanPose/download_mobile_human_pose_working_well.sh
but I'm not sure if it works as your model and I would like to run it using pytorch. :) 

Thank you for your work!

**Comment by SangbumChoi** [comment]
@AivisStud Thanks for asking question. Yes you can use ONNX file from that repository (I officially gave it)!. However, refactoring is still on-going due to adding various technical visualization.

**Comment by AivisStud** [comment]
Hi SangbumChoi,

thanks for the answer. Ok good to know. Unfortunately for me the performance was quite slow (shuttering in pc). but it could be related because of visualization scripts( i used scritps from https://github.com/ibaiGorordo/ONNX-Mobile-Human-Pose-3D and removed heatmaps). I will try to look more deeply in to the visualizations.

I will be waiting for the refactored version. Good luck with your work!:)

Thanks for your answers :)

**Comment by ibaiGorordo** [comment]
Sorry to interrupt here, but yes, the slow speed is probably due to the 3D plot with matplotlib. Additionally, if you want faster speed you might want to try to run it in TensorRT.
