### ISSUE TITLE
about training/test dataset

### ISSUE THREAD

**Issue by liamsun2019** [SangbumChoi/MobileHumanPose#24]
Hi Author,

Thanks for your excellent work.  The default setting are defined in config.py as follows:

trainset_3d = ['MuCo']
trainset_2d = ['MSCOCO']

testset = 'MuPoTS'

Based on your paper, it looks to have 2 different training/test configs, one is Human3.6M+MPII, the other is Muco+COCO.  So which setting is better or they are just two alternatives and any one is applicable? Thanks for your time.

**Comment by SangbumChoi** [comment]
@liamsun2019 Hi, both are applicable. However, there is slight difference with number of joints by corresponding dataset. For the hidden tip, if you are planning for real-world application then you should try like

```
trainset_3d = ['MuCo', 'Human3.5M']
trainset_2d = ['MSCOCO', 'MPII']
```

Above setting will give you best performance.

**Comment by liamsun2019** [comment]
Thanks for your prompt feedback. I will try it out. BTW, just curious when will the new version be released. I believe many readers are looking forward to that.

**Comment by SangbumChoi** [comment]
It has been delayed because of my laziness :( I will try it when time is available
