### ISSUE TITLE
some questions about config

### ISSUE THREAD

**Issue by liamsun2019** [SangbumChoi/MobileHumanPose#25]
Hi Author,

I have some questions about the settings in config.py
a. the default output size is 256x256 and there's an assertion in input size check:
assert input_size[1] in [256]
does it mean other input size cannot be applied? such as 320x320 etc.

b. the default output shape is devided by 8:
output_shape = (input_shape[0]//8, input_shape[1]//8)
can it be changed? e.g, divided by 4 instead. Meanwhile, the default depth_dim is set to 32. Is there any requirement on depth and output_shape? Since I notice there are some reshape operations in soft_max, I am a little confused. Based on the reshape operations, it looks that depth_dim and output_shape need to be the same value.

Wait for your reply, big thanks.

**Comment by SangbumChoi** [comment]
@liamsun2019 
a. If you have ability to modify the code then answer is yes. However only changing input size will cause error.
b. actually this is yes. Also I have tested with different depth_dim and different output_shape to ((nput_shape[0]//16, input_shape[1]/16) but not discussed in paper. depth_dim and output_shape should be the same value if you want to modify.

**Comment by liamsun2019** [comment]
Thanks. I just read the codes in lpnet_ski_concat.py. Looks that you really modified some settings based on original mobilenetv2.  According to your modified nework, the final output size is 32x32 corresponding to input size 256x256. In addition, the output channel from final_layer is joint_num * 32. So, for a specific joint_num, i.e, 21 for MuCo, the output channel number is fixed and 32 should be the depth_dim defined in config.py. Otherwise, the reshape operations in soft max will not make sense. This is my understanding.

**Comment by SangbumChoi** [comment]
Abosulely correct u can modify that 32 into specific number. This 32 is not defined in cofig file but u can modify

**Comment by liamsun2019** [comment]
Got it.  Another question is about the final output of soft_argmax@model.py. Are the output coordinates relative to the output_shape? For instance, if output_shape is 32x32, the output coordinates are then relative to 32, right? If so, some up-scale need to be done to get the final coordinates relative to the actual input image. Need your tips. Thanks for your time.

**Comment by SangbumChoi** [comment]
> Got it.  Another question is about the final output of soft_argmax@model.py. Are the output coordinates relative to the output_shape? For instance, if output_shape is 32x32, the output coordinates are then relative to 32, right? If so, some up-scale need to be done to get the final coordinates relative to the actual input image. Need your tips. Thanks for your time.

Perfect 😀 . Please let me know if u need anything else

**Comment by liamsun2019** [comment]
Thanks. The network seems to be 'top-down' alike, i.e, a detector is needed to get the cropped image which is then passed to the network as the real input. I am curious if the output coordinates are sensitive to the cropped image provied by the detector. What I am concerned is that, if the original image is not cropped precisely, the output coordinates will vibrate accordingly?

**Comment by SangbumChoi** [comment]
@liamsun2019 Now this is area of tip. That you don't have to crop image precisely since the model is robust enough to detect the keypoints in image. However you need some amount of crop for human bounding box!
