### ISSUE TITLE
Small mistake/change in model?

### ISSUE THREAD

**Issue by AivisStud** [SangbumChoi/MobileHumanPose#28]
Hi SangbumChoi,

I was trying to understand your code a little bit and I got a confusion a little bit (I'm new to this so I might be wrong).
I was checking your residual inverted block configuration. according your paper: you modified first 4 layers. here is what i noticed:
![image](https://user-images.githubusercontent.com/94076305/163343910-b7b97563-53fa-404a-9517-ed90535c0812.png)

1st. At first bottleneck you increase the channel output to 64. Looking at the MobilenetV2 structure. shouldn't it go down to 24 and then go up?

2th. bottleneck layers 4,5 has swapped stride. is this a typo or new modification since your paper came out?

thank you for your good work!

**Comment by SangbumChoi** [comment]
@AivisStud Thanks for pointing out I will refactor it considering this changes :)
