### ISSUE TITLE
Will pre-trained model be provided?

### ISSUE THREAD

**Issue by ALISCIFP** [SangbumChoi/MobileHumanPose#30]

**Comment by GKeppler** [comment]
Yes, please provide checkpoints. It is great for other researchers and it also provides more evidence for your results.

**Comment by SangbumChoi** [comment]
@ALISCIFP @GKeppler I never thought about that sorry for inconvinience. I will upload several files that I have trained back in the days (because I can't have any time for re-train this)

**Comment by SangbumChoi** [comment]
https://drive.google.com/drive/folders/146ZFPZyFyRQejB8CBYZ_R26NEXEO4EjI?usp=share_link

Hi, I have shared pytorch model, but you should know that these files may need some minor modification in order to do proper inference (such as size modification).

**Comment by ALISCIFP** [comment]
@SangbumChoi Hi Dr. Choi, Thanks fo sharing for these. Can you specify which file corresponds to which experient configuration in your paper? I mean the correspondence between these pre-trained PyTorch models and experiment configurations.  Thanks!

**Comment by SangbumChoi** [comment]
@ALISCIFP I just uploaded random pth file that I have (I have more random ONNX, TF file also). So I'm not sure which one is the exact configuration of mine... You can re-run my train code.

**Comment by ALISCIFP** [comment]
@SangbumChoi Thanks so much! That's fine. Can you upload all the ONNX, and TF files, please?

**Comment by SangbumChoi** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/156_MobileHumanPose
