### ISSUE TITLE
What is  target_vis = target['vis'], target_have_depth = target['have_depth'] in model.py?

### ISSUE THREAD

**Issue by tkddnjs98** [SangbumChoi/MobileHumanPose#34]
I thought that only 3d joint coordinate x,y,z are needed to train model for 3d dateset, 
But when I analyzed model.py, there are target_vis, target_have_depth for loss function.

```
loss_coord = torch.abs(coord - target_coord) * target_vis
            loss_coord = (loss_coord[:,:,0] + loss_coord[:,:,1] + loss_coord[:,:,2] * target_have_depth)/3.
            return loss_coord
```
Can you explain what they are?

**Comment by SangbumChoi** [comment]
@tkddnjs98 since several 3d human pose estimation repository or paper use 2d dataset, and they don'y have value such as z axis so this is the reason why they have these kinds of variable

**Comment by tkddnjs98** [comment]
Thanks a lot
