### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by tkddnjs98** [SangbumChoi/MobileHumanPose#36]
Hello, I'm trying to train my own dataset using this model.
I'm trying to make this to COCO format.
However, this dataset has problem because it only includes [x, y, z] and no bounding box.
The dataset has 1person per image with [x, y, z(depth)] coordinates. Can I use it? Or should I make bounding box per image?

**Comment by SangbumChoi** [comment]
@tkddnjs98 you should use naive keypoint to bounding box transformation in order to get bounding boxes (such as maxX, maxY)
