### ISSUE TITLE
the coordinate loss

### ISSUE THREAD

**Issue by Berry-Wu** [SangbumChoi/MobileHumanPose#38]
First, thanks for your great work.
I'm new to this field about 3D human pose estimation，I have a base question about the coordinate loss in model.py#L70, 
```
## coordinate loss
loss_coord = torch.abs(coord - target_coord) * target_vis
loss_coord = (loss_coord[:,:,0] + loss_coord[:,:,1] + loss_coord[:,:,2] * target_have_depth)/3.
```
after the L1 loss,why do you let the target_have_depth to multiple the z axis？what's the meanning?

**Comment by SangbumChoi** [comment]
https://github.com/SangbumChoi/MobileHumanPose/blob/a359dd9798e011af3499623d5fbb6dfcbb069a59/data/dataset.py#L13

Hi, it is not actually muliplying z axis, target_have_depth would be either True or False. It is the concept of whether the dataset is consist of 3D or 2D.

**Comment by Berry-Wu** [comment]
It's my fault, thank you for your reply :)
