### ISSUE TITLE
TensorflowLite benchmark

### ISSUE THREAD

**Issue by SonNguyen2510** [SangbumChoi/MobileHumanPose#42]
Dear author,

Did you use quantization when benchmarking your model on Tensorflow framework?
If yes, could you tell me did you use dynamic or full integer quantization?
Thank you.

**Comment by SangbumChoi** [comment]
I think it was dynamic quantization,  but I'm not sure. Sorry for the unclear memorization

**Comment by SonNguyen2510** [comment]
Thank you for your answer
