### ISSUE TITLE
When I run the training code according to your readme, a key error is reported.

### ISSUE THREAD

**Issue by APeiZou** [SangbumChoi/MobileHumanPose#5]
![image](https://user-images.githubusercontent.com/49524647/128145791-711c08f5-af60-4ad8-a3b3-42cee0332f98.png)
When I run the training code according to your readme, a key error is reported. What’s wrong with this？

**Comment by unoShin** [comment]
Use LPSKI instead of LPSKINET

**Comment by APeiZou** [comment]
@unoShin when Use LPSKI，A new problem appeared, and the loss became more and more abnormal。
![image](https://user-images.githubusercontent.com/49524647/128148493-f3787b13-ae3b-49b8-8253-20b5648045b5.png)

**Comment by SangbumChoi** [comment]
@APeiZou Please let me know the difference between epochs, not by batches. If this continues with further epochs that it must be serious bug.

**Comment by unoShin** [comment]
@SangbumChoi Actually it keeps happening until the end of the training.
![1](https://user-images.githubusercontent.com/26159308/128152611-719a3b0e-9f53-421b-8995-71e7eb1c1381.PNG)

**Comment by SangbumChoi** [comment]
@unoShin Thanks for reply. Let me check today and fix the bug, if you need this code urgently then please refer to the past commits.

**Comment by unoShin** [comment]
Also, if I run test.py using that model, the process is killed by out of memory. (It can be due to my hardware spec)
![2](https://user-images.githubusercontent.com/26159308/128152852-391565f0-de29-49d1-b029-011f86cff6c1.PNG)
And if I change vis = True in test.py, then another problem appears.
![image](https://user-images.githubusercontent.com/26159308/128153245-d21dc857-8acb-46b3-a905-9ec632b2427d.png)

**Comment by SangbumChoi** [comment]
> Also, if I run test.py using that model, the process is killed by out of memory. (It can be due to my hardware spec)
> ![2](https://user-images.githubusercontent.com/26159308/128152852-391565f0-de29-49d1-b029-011f86cff6c1.PNG)
> And if I change vis = True in test.py, then another problem appears.
> ![image](https://user-images.githubusercontent.com/26159308/128153245-d21dc857-8acb-46b3-a905-9ec632b2427d.png)

For the above issue I also think it is about hardware specs.
And for the bottom issue please let me know if the error keep shows with the most recent branch

**Comment by APeiZou** [comment]
@SangbumChoi When  I test the epoch 24，the error is big.
![image](https://user-images.githubusercontent.com/49524647/128274171-1100eb63-fb5a-4da0-9aaa-063930b243e8.png)

**Comment by SangbumChoi** [comment]
@APeiZou Can you try --epochs 24-24 instead of just 24? and also next time please give me some additional information (such as training log). It would be more easy to find the errors.

**Comment by wangm-word** [comment]
hi,i I place the dataset as required,but when i train ,it has a bug,can you help me?
![image](https://user-images.githubusercontent.com/72743278/128306355-7b9da5c5-590f-4c92-9b69-79b609571434.png)
@APeiZou 
@unoShin

**Comment by APeiZou** [comment]
@wangm-word 
![image](https://user-images.githubusercontent.com/49524647/128308468-8185a2f8-9e76-4019-9d84-7c0f8ad866e3.png)
have no Muco-3DHP datasets, modified as above  picture.

**Comment by wangm-word** [comment]
thank you a lot ,but i have new proplem
![image](https://user-images.githubusercontent.com/72743278/128310720-88ea4fd4-836b-4a38-871a-2344b0c5ddfe.png)

**Comment by SangbumChoi** [comment]
> thank you a lot ,but i have new proplem
> ![image](https://user-images.githubusercontent.com/72743278/128310720-88ea4fd4-836b-4a38-871a-2344b0c5ddfe.png)

this might because you didn't pull recent branch

**Comment by SangbumChoi** [comment]
Does all of you have fixed this issue? Can I close?

**Comment by wangm-word** [comment]
> Does all of you have fixed this issue? Can I close?

I have saved this issue ,you can close it ,thank you vrey much!
