### ISSUE TITLE
demo proplem

### ISSUE THREAD

**Issue by wangm-word** [SangbumChoi/MobileHumanPose#6]
![image](https://user-images.githubusercontent.com/72743278/128279596-a3f0e070-a648-4635-863b-ae06cf4f8cfc.png)
hi,thank you for your work!How do you get the "root_deep_list" parameter in the demon?

**Comment by SangbumChoi** [comment]
@wangm-word Unfortunately you have to run another deep learning model in order to find out root_depth_list which is https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE

**Comment by wangm-word** [comment]
> @wangm-word Unfortunately you have to run another deep learning model in order to find out root_depth_list which is https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE

thank you a lot! and when you are inferring on the mobile phone, do you also run this network to obtain this parameter?

**Comment by SangbumChoi** [comment]
> > @wangm-word Unfortunately you have to run another deep learning model in order to find out root_depth_list which is https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE
> 
> thank you a lot! and when you are inferring on the mobile phone, do you also run this network to obtain this parameter?

I'm not quite sure that I fully understand your question. However, the parameter such as FLOPS can be calculated by 
https://github.com/SangbumChoi/MobileHumanPose/blob/master/main/summary.py

And for the inference speed, yes it is measured in mobile Phone

**Comment by wangm-word** [comment]
> > > @wangm-word Unfortunately you have to run another deep learning model in order to find out root_depth_list which is https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE
> > 
> > 
> > thank you a lot! and when you are inferring on the mobile phone, do you also run this network to obtain this parameter?
> 
> I'm not quite sure that I fully understand your question. However, the parameter such as FLOPS can be calculated by
> https://github.com/SangbumChoi/MobileHumanPose/blob/master/main/summary.py
> 
> And for the inference speed, yes it is measured in mobile

> > > @wangm-word Unfortunately you have to run another deep learning model in order to find out root_depth_list which is https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE
> > 
> > 
> > thank you a lot! and when you are inferring on the mobile phone, do you also run this network to obtain this parameter?
> 
> I'm not quite sure that I fully understand your question. However, the parameter such as FLOPS can be calculated by
> https://github.com/SangbumChoi/MobileHumanPose/blob/master/main/summary.py
> 
> And for the inference speed, yes it is measured in mobile Phone

haha,sorry,I mean, do you need to use the "root_deep_list" parameter when you infer images on your phone?
![image](https://user-images.githubusercontent.com/72743278/128279596-a3f0e070-a648-4635-863b-ae06cf4f8cfc.png)

**Comment by SangbumChoi** [comment]
> > > > @wangm-word Unfortunately you have to run another deep learning model in order to find out root_depth_list which is https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE
> > > 
> > > 
> > > thank you a lot! and when you are inferring on the mobile phone, do you also run this network to obtain this parameter?
> > 
> > 
> > I'm not quite sure that I fully understand your question. However, the parameter such as FLOPS can be calculated by
> > https://github.com/SangbumChoi/MobileHumanPose/blob/master/main/summary.py
> > And for the inference speed, yes it is measured in mobile
> 
> > > > @wangm-word Unfortunately you have to run another deep learning model in order to find out root_depth_list which is https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE
> > > 
> > > 
> > > thank you a lot! and when you are inferring on the mobile phone, do you also run this network to obtain this parameter?
> > 
> > 
> > I'm not quite sure that I fully understand your question. However, the parameter such as FLOPS can be calculated by
> > https://github.com/SangbumChoi/MobileHumanPose/blob/master/main/summary.py
> > And for the inference speed, yes it is measured in mobile Phone
> 
> haha,sorry,I mean, do you need to use the "root_deep_list" parameter when you infer images on your phone?
> ![image](https://user-images.githubusercontent.com/72743278/128279596-a3f0e070-a648-4635-863b-ae06cf4f8cfc.png)

Oh this demo.py is for computer demo not in mobile devices :)
