### ISSUE TITLE
loss proplem

### ISSUE THREAD

**Issue by wangm-word** [SangbumChoi/MobileHumanPose#8]
thank you for your work!
what's the "vis" and "have_depth" in loss?
![image](https://user-images.githubusercontent.com/72743278/129542915-2ee175d3-d579-431e-8dd8-35e9368f3b53.png)

**Comment by SangbumChoi** [comment]
vis means the joints of the specific image correspond to the human pose
have_depth is means if whether dataset has z axis since we use additional 2D pose dataset

**Comment by wangm-word** [comment]
> vis means the joints of the specific image correspond to the human pose
> have_depth is means if whether dataset has z axis since we use additional 2D pose dataset
thanks！
the value of the joint_vis is joint_num？
